### ISSUE TITLE
Use `Option<()>` or just `()` rather than bool

### ISSUE THREAD

**Issue by shawntabrizi** [gautamdhameja/substrate-account-set#2]
https://github.com/gautamdhameja/substrate-account-set/blob/96c36a84db73b7723c158bd56524f71052419522/src/lib.rs#L28

Since you never actually use the boolean value, there is not reason to store any value at all in storage. Using `()`, you can still check `exists`, but just have that much less storage :)

**Comment by gautamdhameja** [comment]
Tried with `()` but it seems to not working with genesis config. The runtime is not able to find the load the values from genesis config and a storage query returns null on those.

**Comment by shawntabrizi** [comment]
@thiolliere is `()` allowed as config storage?

**Comment by shawntabrizi** [comment]
@gautamdhameja you can ignore this suggestion. Seems like it also causes problems in the UI: https://github.com/polkadot-js/api/issues/1724

**Comment by gui1117** [comment]
if you write:
```rust
WhitelistedAccounts get(whitelisted_accounts) config(): map T::AccountId => (); 
```

Then all query to `<Module<T>>::whitelisted_accountrs()` or `WhilteListedAccounts::get()` will return () because for storage that are not an option, default value is returned in case the value is not found.
Although exist should work as you said.

But I think if you write:
```rust
WhitelistedAccounts get(whitelisted_accounts) config(): map T::AccountId => Option<()>; 
```
Everything should work as you want. get returning None on no value et Some on some value.
If not would be great to have a bug report as this pattern seems quite useful.
